# -*- coding: utf-8 -*-
"""Aula09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6zb6K0cTVqu-P2uYFXpgbXz6LVUhl8X

------

 Laço de repetição for 

------

Laço de repetição for é o laço de repetição mais usado no Python.

A estrutura básica do for é:

for i in range(numero):
....<código a ser repetido>

Dentro do range() deve ser colocado um número inteiro de vezes que você quer que o for faça o loop.
"""

# Exemplo1: Uso do for.

# Faça um programa que mostre na tela números de 0 a 10.

for i in range( 11 ): # Com o range() ele vai começar com o zero e ir até um numeor antes do 11!
    print( i )

# Exemplo2: Uso do for.

# Faça um programa que mostre a taboada do 7.

for i in range(11):
    print(f"7 x {i} = {i*7}")

# Exemplo3: Uso do for.

# Faça um programa que peça 5 notas de um aluno e mostre a média

notasAlunos = [ ] # A lista tem que ser iniciada fora do for"
                  # Se a lista for iniciada dentro do for, a cada loop a lista será apagada!

for i in range(5): 
    nota = float (input(f"Digite a nota {i+1}: "))
    notasAlunos.append(nota)

print(f"A média é: {sum(notasAlunos) / len( notasAlunos )}")

# Não ficou fácil? Agora ao invés de usar 5 variáveis, usamos 1 lista.
